name: CloudFlare Deploy - Explorer UI Dashboard (Production)
on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: "18"
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          VITE_INDEXER_URL: "https://api.buildwithsygma.com"
          VITE_SHARED_CONFIG_URL: "https://sygma-assets-mainnet.s3.us-east-2.amazonaws.com/shared-config-mainnet.json"
          VITE_EXPLORER_URLS: '[{ "id": 1, "url": "https://etherscan.io" }, { "id": 2, "url": "https://khala.subscan.io" }, {"id": 3, "url": "https://phala.subscan.io" }, { "id": 4, "url": "https://cronoscan.com" }, { "id": 5, "url": "https://basescan.org" }, { "id": 6, "url": "https://gnosisscan.io/" }, { "id": 7, "url": "https://polygonscan.com"}]'
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2238a825c5aca59233eab1f221f7aefb
          projectName: sygma-explorer-prod
          directory: ./dist
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
